import { CrossingStatus, ReadCheckStatus, WriteCheckStatus } from '@/types/airlock';

// Demo mock data
export const MOCK_STATUS = {
  github: { connected: true, username: 'operator-dev' },
  slack: { connected: true, workspace: 'AcmeCorp' },
  companion: { online: true, lastSeen: new Date().toISOString(), companionId: 'companion-local-01' },
  user: { id: 'demo-user-001', email: 'operator@acme.dev', displayName: 'Alex Chen' },
};

export const MOCK_CROSSINGS = [
  {
    id: 'cx-001',
    status: 'ready_for_review' as CrossingStatus,
    read_check_status: 'verified' as ReadCheckStatus,
    write_check_status: 'awaiting_approval' as WriteCheckStatus,
    source_repo_owner: 'acme-corp',
    source_repo_name: 'platform-api',
    source_issue_number: 342,
    source_title: 'Production database connection pool exhausted',
    source_issue_url: 'https://github.com/acme-corp/platform-api/issues/342',
    source_excerpt: 'The connection pool on prod-db-primary has been fully exhausted since 14:32 UTC. All new requests are queuing. Immediate investigation required.',
    source_labels: ['severity:critical', 'component:database', 'env:production'],
    source_verified_at: new Date(Date.now() - 60000).toISOString(),
    destination_kind: 'slack_post_message',
    destination_channel_id: 'C0123INCIDENTS',
    destination_channel_label: '#incidents',
    proposed_text: '🚨 [platform-api#342] Production database connection pool exhausted — Connection pool on prod-db-primary fully exhausted since 14:32 UTC. Immediate investigation required. https://github.com/acme-corp/platform-api/issues/342',
    proposed_payload_hash: 'sha256:a1b2c3d4e5f6',
    policy_result: 'allow_review',
    policy_reason_code: null,
    policy_reason_text: null,
    rationale: 'Escalating critical database issue to incident channel for operator review.',
    created_at: new Date(Date.now() - 120000).toISOString(),
    updated_at: new Date(Date.now() - 60000).toISOString(),
  },
  {
    id: 'cx-002',
    status: 'blocked_pre_review' as CrossingStatus,
    read_check_status: 'verified' as ReadCheckStatus,
    write_check_status: 'blocked' as WriteCheckStatus,
    source_repo_owner: 'acme-corp',
    source_repo_name: 'platform-api',
    source_issue_number: 340,
    source_title: 'Update README with new deployment steps',
    source_issue_url: 'https://github.com/acme-corp/platform-api/issues/340',
    source_excerpt: 'The deployment documentation needs updating to reflect the new CI/CD pipeline changes.',
    source_labels: ['docs', 'low-priority'],
    source_verified_at: new Date(Date.now() - 300000).toISOString(),
    destination_kind: 'slack_post_message',
    destination_channel_id: 'C9999RANDOM',
    destination_channel_label: '#random',
    proposed_text: 'README update needed for platform-api. See issue #340.',
    proposed_payload_hash: 'sha256:f6e5d4c3b2a1',
    policy_result: 'block',
    policy_reason_code: 'destination_channel_not_allowed',
    policy_reason_text: 'Blocked: destination channel #random is not allowed. Only #incidents is permitted.',
    rationale: 'Attempting alternate routing.',
    created_at: new Date(Date.now() - 300000).toISOString(),
    updated_at: new Date(Date.now() - 300000).toISOString(),
  },
  {
    id: 'cx-003',
    status: 'sent' as CrossingStatus,
    read_check_status: 'verified' as ReadCheckStatus,
    write_check_status: 'sent' as WriteCheckStatus,
    source_repo_owner: 'acme-corp',
    source_repo_name: 'auth-service',
    source_issue_number: 128,
    source_title: 'OAuth token refresh loop detected in production',
    source_issue_url: 'https://github.com/acme-corp/auth-service/issues/128',
    source_excerpt: 'Token refresh endpoint returning 503 intermittently, causing retry storms.',
    source_labels: ['severity:high', 'component:auth'],
    source_verified_at: new Date(Date.now() - 3600000).toISOString(),
    destination_kind: 'slack_post_message',
    destination_channel_id: 'C0123INCIDENTS',
    destination_channel_label: '#incidents',
    proposed_text: '⚠️ [auth-service#128] OAuth token refresh loop detected — Token refresh endpoint returning 503. https://github.com/acme-corp/auth-service/issues/128',
    proposed_payload_hash: 'sha256:x1y2z3w4',
    policy_result: 'allow_review',
    policy_reason_code: null,
    policy_reason_text: null,
    approved_by_sub: 'demo-user-001',
    approved_at: new Date(Date.now() - 3500000).toISOString(),
    slack_message_ts: '1234567890.123456',
    rationale: 'Escalating auth service issue.',
    created_at: new Date(Date.now() - 3700000).toISOString(),
    updated_at: new Date(Date.now() - 3500000).toISOString(),
  },
];

export const MOCK_EVENTS = [
  {
    id: 'ev-001',
    crossing_id: 'cx-001',
    auth0_user_sub: 'demo-user-001',
    event_type: 'intent.received',
    actor_type: 'companion',
    actor_id: 'companion-local-01',
    message: 'Intent received from local companion',
    details_json: null,
    created_at: new Date(Date.now() - 120000).toISOString(),
  },
  {
    id: 'ev-002',
    crossing_id: 'cx-001',
    auth0_user_sub: 'demo-user-001',
    event_type: 'source.verification.started',
    actor_type: 'system',
    actor_id: null,
    message: 'Verifying GitHub issue acme-corp/platform-api#342',
    details_json: null,
    created_at: new Date(Date.now() - 110000).toISOString(),
  },
  {
    id: 'ev-003',
    crossing_id: 'cx-001',
    auth0_user_sub: 'demo-user-001',
    event_type: 'source.verification.succeeded',
    actor_type: 'system',
    actor_id: null,
    message: 'GitHub source verified through connected account',
    details_json: { issueTitle: 'Production database connection pool exhausted' },
    created_at: new Date(Date.now() - 100000).toISOString(),
  },
  {
    id: 'ev-004',
    crossing_id: 'cx-001',
    auth0_user_sub: 'demo-user-001',
    event_type: 'policy.allowed.review',
    actor_type: 'system',
    actor_id: null,
    message: 'Policy evaluation passed. Crossing ready for human review.',
    details_json: { result: 'allow_review' },
    created_at: new Date(Date.now() - 90000).toISOString(),
  },
];
